# Generated by Django 3.0 on 2020-07-13 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('banner_pic', models.ImageField(upload_to='banners')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Brandname', models.CharField(max_length=20)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='media/brands/')),
                ('Country', models.CharField(choices=[('RU', 'Russia'), ('CN', 'China'), ('JP', 'Japan'), ('US', 'United States'), ('EG', 'Egypt')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Merch', models.CharField(max_length=200, null=True, verbose_name='product')),
                ('quantity', models.CharField(max_length=200, null=True, verbose_name='Quantity')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='added on')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='address')),
                ('firstname', models.CharField(max_length=200, null=True, verbose_name='first name')),
                ('lastname', models.CharField(max_length=200, null=True, verbose_name='last name')),
                ('contactphone', models.CharField(max_length=200, null=True, verbose_name='contact phone')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Email', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('Usage', models.CharField(max_length=50)),
                ('Price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('Description', models.CharField(max_length=200)),
                ('Picture', models.ImageField(blank=True, null=True, upload_to='media/products/')),
                ('PublishDate', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CYBERstore.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='price')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='added on')),
                ('Merch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CYBERstore.Merch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
