# Generated by Django 3.1.5 on 2021-03-22 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_info',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='age'),
        ),
        migrations.AddField(
            model_name='user_profile_info',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_pic',
            field=models.ImageField(upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='user_profile_info',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
