# Generated by Django 3.0 on 2020-07-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CYBERstore', '0003_auto_20200714_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
