# Generated by Django 3.0 on 2020-07-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CYBERstore', '0004_auto_20200714_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='subscribed',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
